// Generated
package org.ton.bytecode

val tvmDefaultInstructionList = listOf(
    TvmAppActionsChangelibInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsRawreserveInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsRawreservexInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsSendmsgInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsSendrawmsgInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsSetcodeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppActionsSetlibcodeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrLdmsgaddrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrLdmsgaddrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrParsemsgaddrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrParsemsgaddrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrRewritestdaddrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrRewritestdaddrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrRewritevaraddrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppAddrRewritevaraddrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigConfigdictInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigConfigoptparamInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigConfigparamInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetforwardfeeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetforwardfeesimpleInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetgasfeeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetgasfeesimpleInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetoriginalfwdfeeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetparamInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmAppConfigGetprecompiledgasInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGetstoragefeeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigGlobalidInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigPrevkeyblockInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppConfigPrevmcblocksInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsAggregateInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsAggregateverifyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsFastaggregateverifyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1AddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1IngroupInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1IszeroInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1MulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1MultiexpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1NegInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1SubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG1ZeroInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2AddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2IngroupInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2IszeroInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2MulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2MultiexpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2NegInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2SubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsG2ZeroInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsMapToG1Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsMapToG2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsPairingInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsPushrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoBlsVerifyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoChksignsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoChksignuInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoEcrecoverInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashcuInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextBlake2bInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextKeccak256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextKeccak512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextSha256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextSha512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextaBlake2bInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextaKeccak256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextaKeccak512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextaSha256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextaSha512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextarBlake2bInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextarKeccak256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextarKeccak512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextarSha256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextarSha512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextrBlake2bInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextrKeccak256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextrKeccak512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextrSha256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashextrSha512Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoHashsuInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoP256ChksignsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoP256ChksignuInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255AddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255FromhashInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255MulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255MulbaseInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255PushlInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255QaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255QmulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255QmulbaseInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255QsubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255QvalidateInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255SubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoRist255ValidateInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCryptoSha256uInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyLdgramsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyLdvarint16Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyLdvarint32Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyLdvaruint32Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyStgramsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyStvarint16Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyStvarint32Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppCurrencyStvaruint32Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGasAcceptInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGasCommitInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGasGasconsumedInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGasSetgaslimitInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGlobalGetglobInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmAppGlobalGetglobvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppGlobalSetglobInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmAppGlobalSetglobvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppMiscCdatasizeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppMiscCdatasizeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppMiscSdatasizeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppMiscSdatasizeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppRndAddrandInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppRndRandInst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppRndRandu256Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmAppRndSetrandInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicAddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicAddconstInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmBasicDecInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicIncInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicMulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicMulconstInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmBasicNegateInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicSubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmBasicSubrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAdddivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAdddivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAdddivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAddrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivAddrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivAddrshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAddrshiftmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAddrshiftmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivAddrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivDivInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivDivcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivDivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivDivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivDivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivDivrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftadddivmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftadddivmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftadddivmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftadddivmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftadddivmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftadddivmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftdivrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftdivrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivLshiftmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivLshiftmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivModpow2VarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModpow2cInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivModpow2cVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModpow2rInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivModpow2rVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivModrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuladddivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuladddivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuladddivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuladdrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMuladdrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMuladdrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMuldivInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuldivcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuldivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuldivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuldivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMuldivrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulmodpow2VarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodpow2cInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulmodpow2cVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodpow2rInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulmodpow2rVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftcmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivMulrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivMulrshiftrmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivRshiftcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivRshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivRshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmDivRshiftrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmDivRshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmLogicalAbsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalAndInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalBitsizeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalFitsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmLogicalFitsxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalLshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmLogicalLshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalMaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalMinInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalMinmaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalNotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalOrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalPow2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalRshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmLogicalRshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalUbitsizeInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalUfitsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmLogicalUfitsxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmLogicalXorInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQadddivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQadddivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQadddivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQaddrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQaddrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQaddrshiftmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQaddrshiftmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQaddrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQandInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdecInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQdivrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQfitsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQfitsxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQincInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftadddivmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftadddivmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftadddivmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftadddivmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftadddivmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftadddivmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftdivrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftdivrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftmodcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQlshiftmodrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQlshiftmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmodpow2VarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodpow2cInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmodpow2cVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodpow2rInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmodpow2rVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuladddivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuladddivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuladddivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuladdrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmuladdrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmuladdrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmuldivInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuldivcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuldivmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuldivmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuldivmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmuldivrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulmodpow2VarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodpow2cInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulmodpow2cVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodpow2rInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulmodpow2rVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulmodrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulrshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulrshiftcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftcmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftcmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQmulrshiftrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftrmodInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQmulrshiftrmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQnegateInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQorInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQpow2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQrshiftVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftcInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQrshiftcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftcmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQrshiftmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQrshiftmodVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftmodcVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftmodrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQrshiftrVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQrshiftrmodInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQsubInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQsubrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQufitsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmArithmQuietQufitsxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmArithmQuietQxorInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBbitrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBbitsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkbitrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkbitrefsqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkbitsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildBchkbitsVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkbitsqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildBchkbitsqVarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBchkrefsqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBdepthInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBrembitrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBrembitsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildBremrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildEndcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildEndxcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildNewcInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrefqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrefrAltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrefrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrefrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStbrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStiAltInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStiInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStile4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStile8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStiqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStirInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStirqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStixInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStixqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStixrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStixrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStonesInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStref2constInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmCellBuildStrefAltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStrefconstInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmCellBuildStrefqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStrefrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStrefrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStsameInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStsliceAltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStsliceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStsliceconstInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmCellBuildStsliceqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStslicerInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStslicerqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStuAltInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStuInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStule4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStule8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStuqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildSturInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildSturqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellBuildStuxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStuxqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStuxrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStuxrqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellBuildStzeroesInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseCdepthInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseCdepthiInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseCdepthixInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseChashiInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseChashixInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseClevelInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseClevelmaskInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseCtosInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseEndsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdiAltInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdiInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdile4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdile4qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdile8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdile8qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdiqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdixInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdixqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdonesInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdrefrtosInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdsameInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdsliceAltInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdsliceInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdsliceqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdslicexInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdslicexqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLduAltInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLduInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLdule4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdule4qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdule8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdule8qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLduqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseLduxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLduxqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseLdzeroesInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldiInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldile4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldile4qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldile8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldile8qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldiqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldixInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldixqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldrefidxInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldrefvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldsliceInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldsliceqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldslicexInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldslicexqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePlduInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePldule4Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldule4qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldule8Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePldule8qInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePlduqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParsePlduxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePlduxqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParsePlduzInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCellParseSbitrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSbitsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkbitrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkbitrefsqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkbitsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkbitsqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSchkrefsqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseScutfirstInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseScutlastInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdbeginsInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmCellParseSdbeginsqInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmCellParseSdbeginsxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdbeginsxqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdcutfirstInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdcutlastInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdepthInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdskipfirstInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdskiplastInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSdsubstrInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSplitInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSplitqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSrefsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSskipfirstInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSskiplastInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseSubsliceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseXctosInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseXloadInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCellParseXloadqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCodepageSetcpInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCodepageSetcpSpecialInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCodepageSetcpxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntChknanInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntCmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntEqintInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCompareIntEqualInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntGeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntGreaterInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntGtintInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCompareIntIsnanInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntLeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntLessInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntLessintInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCompareIntNeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareIntNeqintInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmCompareIntSgnInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdcntlead0Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdcntlead1Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdcnttrail0Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdcnttrail1Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdemptyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdeqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdfirstInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdlexcmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdpfxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdpfxrevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdppfxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdppfxrevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdpsfxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdpsfxrevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdsfxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSdsfxrevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSemptyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmCompareOtherSremptyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmConstDataPushcontInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmConstDataPushcontShortInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmConstDataPushrefInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmConstDataPushrefcontInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmConstDataPushrefsliceInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmConstDataPushsliceInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmConstDataPushsliceLongInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmConstDataPushsliceRefsInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmConstIntPushint16Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmConstIntPushint4Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmConstIntPushint8Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmConstIntPushintLongInst(
        TvmInstLambdaLocation(0),
        "0",
    ),
    TvmConstIntPushnanInst(
        TvmInstLambdaLocation(0),
    ),
    TvmConstIntPushnegpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmConstIntPushpow2Inst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmConstIntPushpow2decInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContBasicBranchInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicCallccInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicCallccargsInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmContBasicCallccvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicCallrefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContBasicCallxargsInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmContBasicCallxargsVarInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContBasicCallxvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicExecuteInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicJmprefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContBasicJmprefdataInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContBasicJmpxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicJmpxargsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContBasicJmpxdataInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicJmpxvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicRetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicRetaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicRetargsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContBasicRetdataInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicRetvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContBasicRunvmInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContBasicRunvmxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalCondselInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalCondselchkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfbitjmpInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContConditionalIfbitjmprefInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContConditionalIfelseInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfelserefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfjmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfjmprefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfnbitjmpInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContConditionalIfnbitjmprefInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContConditionalIfnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfnotjmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfnotjmprefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfnotrefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfnotretInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfnotretaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfrefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfrefelseInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfrefelserefInst(
        TvmInstLambdaLocation(0),
        TvmInstList(emptyList()),
        TvmInstList(emptyList()),
    ),
    TvmContConditionalIfretInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContConditionalIfretaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContCreateBlessInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContCreateBlessargsInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmContCreateBlessvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContDictCalldictInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContDictCalldictLongInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContDictJmpdictInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContDictPreparedictInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContLoopsAgainInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsAgainbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsAgainendInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsAgainendbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsRepeatInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsRepeatbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsRepeatendInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsRepeatendbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsUntilInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsUntilbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsUntilendInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsUntilendbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsWhileInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsWhilebrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsWhileendInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContLoopsWhileendbrkInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersAtexitInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersAtexitaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersBoolevalInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersComposInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersComposaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersComposbothInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersInvertInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersPopctrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersPopctrxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersPopsaveInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersPushctrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersPushctrxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersSamealtInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersSamealtsaveInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersSaveInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersSavealtInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersSavebothInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersSetaltctrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersSetcontctrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersSetcontctrxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersSetexitaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersSetretctrInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContRegistersThenretInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContRegistersThenretaltInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContStackReturnargsInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmContStackReturnvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContStackSetcontargsNInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmContStackSetcontvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmContStackSetnumvarargsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDebugDebugInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmDebugDebugstrInst(
        TvmInstLambdaLocation(0),
        TvmCell(TvmCellData(""), emptyList()),
    ),
    TvmDictDeleteDictdelInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictdelgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictdelgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictidelInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictidelgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictidelgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictudelInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictudelgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictDeleteDictudelgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictigetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictigetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictugetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictGetDictugetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictgetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictigetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictisetgetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictsetgetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictugetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMayberefDictusetgetoptrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictimaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictimaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiremmaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiremmaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiremminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictiremminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictmaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictmaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictremmaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictremmaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictremminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictremminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictumaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictumaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictuminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDictuminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDicturemmaxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDicturemmaxrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDicturemminInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictMinDicturemminrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictgetnextInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictgetnexteqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictgetprevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictgetpreveqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictigetnextInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictigetnexteqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictigetprevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictigetpreveqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictugetnextInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictugetnexteqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictugetprevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictNextDictugetpreveqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictconstgetjmpInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmDictPrefixPfxdictdelInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictgetexecInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictgetjmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictgetqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictreplaceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictPrefixPfxdictsetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialLddictInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialLddictqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialLddictsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialPlddictInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialPlddictqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialPlddictsInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialSkipdictInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSerialStdictInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictaddbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictaddgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictiaddbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictiaddgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictireplacebInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictireplacegetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictisetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictisetgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictreplacebInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictreplacegetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictsetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictsetgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictuaddbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictuaddgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictureplacebInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictureplacegetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictusetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetBuilderDictusetgetbInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictaddgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictaddgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictaddrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictiaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictiaddgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictiaddgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictiaddrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictireplaceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictireplacegetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictireplacegetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictireplacerefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictisetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictisetgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictisetgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictisetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictreplaceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictreplacegetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictreplacegetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictreplacerefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictsetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictsetgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictsetgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictsetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictuaddInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictuaddgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictuaddgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictuaddrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictureplaceInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictureplacegetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictureplacegetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictureplacerefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictusetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictusetgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictusetgetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSetDictusetrefInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictigetexecInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictigetexeczInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictigetjmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictigetjmpzInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictpushconstInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmDictSpecialDictugetexecInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictugetexeczInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictugetjmpInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSpecialDictugetjmpzInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdictgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdictigetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdictirpgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdictrpgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdictugetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmDictSubSubdicturpgetInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowShortInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowanyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowanyifInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowanyifnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowargInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowarganyInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowarganyifInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowarganyifnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsThrowargifInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowargifnotInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowifInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowifShortInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowifnotInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsThrowifnotShortInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmExceptionsTryInst(
        TvmInstLambdaLocation(0),
    ),
    TvmExceptionsTryargsInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackBasicNopInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackBasicPopInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackBasicPushInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackBasicXchg0iInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackBasicXchg0iLongInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackBasicXchg1iInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackBasicXchgIjInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexBlkdrop2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexBlkdropInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackComplexBlkpushInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexBlkswapInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexBlkswxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexChkdepthInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexDepthInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexDrop2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexDropxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexDup2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexMinusrollxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexOnlytopxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexOnlyxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexOver2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexPickInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexPopLongInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackComplexPu2xcInst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexPush2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexPush3Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexPushLongInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmStackComplexPuxc2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexPuxcInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexPuxcpuInst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexReverseInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexRevxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexRollxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexRotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexRotrevInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexSwap2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexTuckInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexXc2puInst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexXchg2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexXchg3AltInst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexXchg3Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexXchgxInst(
        TvmInstLambdaLocation(0),
    ),
    TvmStackComplexXcpu2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmStackComplexXcpuInst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmStackComplexXcpuxcInst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmTupleExplodeInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleExplodevarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleIndex2Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
    ),
    TvmTupleIndex3Inst(
        TvmInstLambdaLocation(0),
        0,
        0,
        0,
    ),
    TvmTupleIndexInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleIndexqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleIndexvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleIndexvarqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleIsnullInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleIstupleInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleLastInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullrotrif2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullrotrifInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullrotrifnot2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullrotrifnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullswapif2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullswapifInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullswapifnot2Inst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleNullswapifnotInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleQtlenInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleSetindexInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleSetindexqInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleSetindexvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleSetindexvarqInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleTlenInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleTpopInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleTpushInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleTupleInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleTuplevarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleUnpackfirstInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleUnpackfirstvarInst(
        TvmInstLambdaLocation(0),
    ),
    TvmTupleUntupleInst(
        TvmInstLambdaLocation(0),
        0,
    ),
    TvmTupleUntuplevarInst(
        TvmInstLambdaLocation(0),
    ),
)
